src/lib.rs

I send a pull request a earlier today, but didn't verify that it actually worked :P Now I've done that. (The setter needed to be named `setContentsScale`, not `contentsScale`.)
I need this setter to be able to set right scaling factor for the layer.
There's one but: I also added the definition for the CGFloat type. However, this type is already defined in core-graphics crate. It's just a one type, but if there is more redundancy, it should be considered to depend on core-graphics, since the types from there are used quite throughly.

Added setter for contentsScale

---

Cargo.toml
examples/caps/main.rs
examples/indirect/main.rs
examples/library/main.rs
examples/reflection/main.rs
examples/window/main.rs
src/argument.rs
src/buffer.rs
src/commandbuffer.rs
src/commandqueue.rs
src/depthstencil.rs
src/device.rs
src/drawable.rs
src/encoder.rs
src/heap.rs
src/lib.rs
src/library.rs
src/pipeline.rs
src/renderpass.rs
src/resource.rs
src/sampler.rs
src/texture.rs
src/vertexdescriptor.rs

This is very WIP, I just wanted to make sure this is the direction we want to go before I do the rest of the changes. The one file that is pretty much finished is `device.rs`.
As it stands `metal-rs` mostly leaves it to the user to determine lifetimes and remember to release objects. To rectify this we can use the [foreign-types](https://docs.rs/foreign-types/0.3.0/foreign_types/index.html) crate, which creates a `str`/`String`-type dichotomy for arbitrary C types. 
So far I'm following the convention that other ObjC crates like [core-graphics](https://github.com/servo/core-graphics-rs) do and using the naming convention `*mut MTLFoo` for the raw opaque pointer, `Foo` for the owned pointer, and `&FooRef` for the unowned pointer. Incoming arguments are always `&FooRef`, and return values …

Improve memory safety

---

examples/indirect/main.rs
examples/library/main.rs
examples/reflection/main.rs
examples/window/main.rs
src/encoder.rs
src/heap.rs
src/lib.rs
src/vertexdescriptor.rs

There were some optional arguments/return values that were not indicated as such.

Fix some optional arguments

---

examples/reflection/main.rs
examples/window/main.rs
src/library.rs

Add initial support for `MTLFunctionConstantValues` to use in gfx specialization constants.
Please take a look and let me know if this seems right. I'm not sure how the deallocations are supposed to work, but I've tried to follow the other examples.
Note this changes the signature of `get_function`. I can introduce a separate function instead if that's preferable.

Add function constants

---

Cargo.toml
src/sampler.rs

Noticed that a couple of Metal sampler states were not supported for SamplerDescriptorRef, including border color that I needed. 
So have exposed the border color and the remaining missing ones such as lod average, normalized coordinates & support argument buffers.

Add additional sampler states

---

Cargo.toml
examples/compute/embedded-lib.rs
src/device.rs
src/library.rs

This method comes handy when you want to embed metallib in your code during build process, as shown in the `embedded-lib` example.

Add `Device::new_library_with_data` method

---

src/device.rs

I don't have access to a MacOS device right now, but this should compile and run fine. If you would like to wait a couple days I might be able to get access to an Apple device to test this on. More documentation found here https://developer.apple.com/documentation/metal/mtldevice/2915737-registryid

Add device registryID

---

Cargo.toml
src/vertexdescriptor.rs

Add more vertex formats

---

src/constants.rs
src/pipeline/compute.rs
src/texture.rs

Metal docs indicate this property to be read-only. (breaking change?..)

Remove set_buffers on compute pipeline descriptor

---

src/constants.rs

There were a couple missing formats from the [list](https://developer.apple.com/documentation/metal/mtlpixelformat).

Added missing extended range formats

---

src/device.rs

What I think is happening is that the library object keeps a reference to the error, so we shouldn't release it if the library is created.

Fix the zombie error of shader compilation

---

Cargo.toml
src/argument.rs
src/capturemanager.rs
src/depthstencil.rs
src/heap.rs
src/lib.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/renderpass.rs
src/sampler.rs
src/texture.rs
src/vertexdescriptor.rs

- Uses [objc's new `class` macro](https://github.com/SSheldon/rust-objc/issues/65) to cache all class accesses
- Bumps the crate version to 0.10.3

Cache class access

---

Cargo.toml
examples/window/main.rs
src/lib.rs

This is based on the work in this PR #60 by @Michael-Lfx which has not yet been accepted. I am guessing it's abandoned? If not feel free to reject this.
I, too, want this feature merged to help get `metal` (and ultimately `gfx`) building on iOS.

fix iOS: use CGSize instead of NSSize. this is the correct type anyway

---

src/device.rs

On iOS, `Device::all()` now returns `vec![Device::system_default()]`

[ios] MTLCopyAllDevices is not supported on iOS

---

Cargo.toml
examples/caps/main.rs
examples/compute/compute-argument-buffer.rs
examples/compute/main.rs
examples/reflection/main.rs
src/argument.rs
src/commandbuffer.rs
src/device.rs
src/heap.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/renderpass.rs
src/resource.rs
src/sampler.rs
src/texture.rs
src/vertexdescriptor.rs

While working on getting the gfx/quad example going, I ran into some metal calls that are unsupported on iOS. So I did a pass on all the ffi for os compatibility, and fixed things where I could.
- metal-rs is using some private APIs, and apple has a history of rejecting apps from the app store for doing that
- there's no managed memory on iOS
- there's no layered rendering on iOS
- iOS 8.0 is missing some features from osx 10.11
- iOS 9.0 is roughly equivalent in metal support to osx 10.11
- iOS 10.0 is roughly equivalent in metal support to osx 10.12
- iOS 11.0 is roughly equivalent in metal support to osx 10.13
I added a bunch of comments above things that were unsupported on various os versions. Should I leave those in or nuke'em?
This breaks gfx-rs on iOS. I'll make a PR there shortly …

[iOS] audit msg_send! for ios/tvos compatibility

---

src/device.rs

Ran into that this field for detecting eGPUs wasn't exposed, which is a simple add.

Expose missing MTLDevice::is_removable

---

Cargo.toml
src/device.rs

- Add in new MTLFeatureSets.
- Changed the private `os_version` function to return the minor version on macos.
[source](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf)
Edit:
I'm trying to make `gfx-backend-metal` work on iOS < 12. Layered rendering support was just added in iOS 12, and is the main motivation for updating the MTLFeatureSets.

update feature sets

---

src/library.rs

Missed this from the last PR. `0.14.0` has not been published, so I think this can squeeze in without a version bump.
@kvark Is there anything else in metal-rs that should be updated when new OS Versions come out? If so, I'll try and add it into this PR.

add MTLLanguageVersion 2.1

---

src/library.rs

Change `Library::function_names` to return `Vec<String>`

---

src/device.rs

Fixes rust-windowing/winit#1103

Fix device reference ownership in `Device::all()`

---

Cargo.toml

The version of winit used in the window example pins an old version of cocoa lacking a soundness fix (servo/core-foundation-rs#340) for undefined behavior in an upcoming version of rust (rust-lang/rust#65355).
Testing done: ran the window example after this change; it compiles and looks fine!

Bump winit

---

src/device.rs
src/encoder.rs
src/pipeline/render.rs

This PR adds support for Vertex Amplification which is a new feature in Metal. Details of vertex amplification is available here: https://developer.apple.com/documentation/metal/generating_multiple_output_vertex_streams_from_one_input_stream?language=objc

Support Vertex Amplification.

---

examples/texture/.gitignore
examples/texture/build.rs
examples/texture/shader_types/shader_types.h

Because the `OUT_DIR` environment variable can change, the shader bindings cache would get invalidated sometimes leading to a recompilation of shader bindings.
Generating the bindings is a slow process and should be avoided.
This PR creates a directory in the crate to use for caching since having a consistent cache directory means shader type re-compilation becomes rare.
To further reduce the cost of these bindings, I changed the `shader_types.rs` file to only include `simd/vector_types.h` instead of all of `simd/simd.h`. 
This takes a `cargo build -p texture` after editing `shader_types.h` from 16seconds to around 9.7 seconds on my machine (effectively all of that time is spent generating the Rust bindings).
We're really only using one type from that file (vector_float2), but I didn't …

Use more persistent shader type cache dir

---

Cargo.toml
examples/window/main.rs
src/lib.rs
src/pipeline/compute.rs

This is a little bit risky, since there are parts of `cocoa` that we expose in public API (e.g. `NSUInteger`), so updating the breaking version of it is technically also a breaking change... But it's fine as long as both versions of cocoa just typedef it to the same thing, e.g. `u64`.
If there is a way in Rust to know *all* of the public uses of a dependency, it would be handy here.

[0.18] Bump dependencies

---

Cargo.toml
examples/texture/Cargo.toml
src/argument.rs
src/buffer.rs
src/device.rs
src/encoder.rs
src/heap.rs
src/indirect_encoder.rs
src/lib.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/renderpass.rs
src/resource.rs
src/sampler.rs
src/texture.rs
src/types.rs
src/vertexdescriptor.rs

This replaces the implicit dependency on core-graphics with one on
core-graphics-types which should reduce dependency churn.
Also fewer dependencies means less build time.

Switch from cocoa to cocoa_foundation.

---

bors.toml

I think the `Build` status in bors should be `build (stable)` (optionally `build (nightly)` too) to match the status names reported under the `ci` workflow in GitHub Actions.
This change uses the stable build status only, so PR merges aren't blocked if nightly builds fail.

Use stable build status for bors

---

Cargo.toml
examples/events/main.rs
examples/fence/main.rs
src/commandbuffer.rs
src/device.rs
src/encoder.rs
src/lib.rs
src/sync.rs

This PR adds Metal's sync primitives - Event, SharedEvent, Fence.
`SharedEvent.notify` stuff is a bit messy, but I couldn't find a better way.
ref: https://github.com/gfx-rs/metal-rs/issues/178

Add sync primitives 

---

src/device.rs

Adds the following APIs:
- https://developer.apple.com/documentation/metal/mtldevice/3229025-hasunifiedmemory
- https://developer.apple.com/documentation/metal/mtldevice/2369280-recommendedmaxworkingsetsize
- https://developer.apple.com/documentation/metal/mtldevice/3114007-maxtransferrate

Add DeviceRef::{has_unified_memory, recommended_max_working_set_size, max_tranfer_rate}

---

examples/window/main.rs

Without this PR:
After this PR:
I haven't tested the change of scale factor, but it looks reasonable :)

window example: Fix rendering on hdpi screens

---

src/device.rs

This call SIGSEGVs on my system (10.15.7). Why? And will this leak memory? I have no idea.

Prevent SIGSEGV when returning errors from new_library_with_source

---

src/encoder.rs

As I understand it all Ref objects need to use &s. FYI this change is somewhat blind because my metal backend isn't bootstrapped enough to properly test it yet, so feel free to sit on it until I can :)

Use &FenceRef instead of FenceRef in RenderCommandEncoder

---

examples/caps/main.rs
src/device.rs

See https://developer.apple.com/documentation/metal/mtldevice/2966563-maxbufferlength?language=objc

Add maxBufferLength method

---

examples/circle/main.rs
src/device.rs
src/pipeline/compute.rs
src/pipeline/render.rs

As mentioned in https://github.com/gfx-rs/gfx/issues/3716#issuecomment-813698647, we can use [`MTLBinaryArchive`](https://developer.apple.com/documentation/metal/mtlbinaryarchive)s to cache pipelines to disk. This feature was really not clear to me, and seems to be best documented in the WWDC 2020 video [Build GPU Binaries with Metal](https://developer.apple.com/videos/play/wwdc2020/10615/).
Binary Archives were partially implemented, but could not be used so this PR adds that functionality. I modified the circle example to use one but it's possible that making a new example would make more sense. I've tested that the binary archive is indeed written to with the write format, ~~but I've had some trouble creating a pipeline with `MTLPipelineOption::FailOnBinaryArchiveMiss` to check that …

Finish up the implementation of Binary Archives

---

src/lib.rs

This allows rendering HDR content out to display by setting `wantsExtendedDynamicRangeContent`. Tested to work with gfx-hal & wgpu when using `Rgba16Float` swapchain formats. There is more work to be done when it comes to setting [EDR metadata](https://developer.apple.com/documentation/quartzcore/cametallayer/3182052-edrmetadata), but I wanted to get this small change out first.

Add initial HDR support

---

Cargo.toml
examples/caps/main.rs
examples/circle/main.rs
examples/shader-dylib/main.rs
examples/window/main.rs
src/argument.rs
src/device.rs
src/drawable.rs
src/encoder.rs
src/heap.rs
src/indirect_encoder.rs
src/lib.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/renderpass.rs
src/resource.rs
src/sampler.rs
src/texture.rs
src/types.rs
src/vertexdescriptor.rs

`core-graphics-types` is a smaller dependency, which I think we can accept to depend on across the stack.
`cocoa-foundation` doesn't appear to be necessary.

Replace cocoa-foundation dependency to core-graphics-types

---

src/device.rs

This adds support for creating buffers without copies via `newBufferWithBytesNoCopy:length:options:deallocator:`.
https://developer.apple.com/documentation/metal/mtldevice/1433382-newbufferwithbytesnocopy?language=objc

add new_buffer_with_bytes_no_copy

---

Cargo.toml

Update `winit` dependency to fix `expected bool, found integer` error at `window.setFrame_display_(current_rect, 0)` and `expected bool, found i8` at `(marked_text.length() > 0) as i8`. rustc 1.56.1 at Apple M1 8/8 MacBook Air for `window example`

Update `winit` dependency

---

examples/reflection/main.rs
src/argument.rs
src/device.rs
src/pipeline/render.rs

- There is no need to allocate `MTLRenderPipelineReflection` when calling `newRenderPipelineStateWithDescriptor` with reflection.
- Adds array wrappers to iterate over reflection information.
- Removes `new_render_pipeline_state_with_fail_on_binary_archive_miss` (refactored `new_render_pipeline_state_with_reflection` covers it).
- Exposes `MTLPipelineOption`
- Access reflection for compute pipeline.
- Update relevant documentation.
Output from reflection example:
```
Vertex arguments: 
<MTLBufferArgument: 0x6000010980c0>
Name = vertex_array 
Type = MTLArgumentTypeBuffer 
Access = MTLArgumentAccessReadWrite 
LocationIndex = 0 
IsActive = 1 
ArrayLength = 1 
TypeInfo = 
DataType = MTLDataTypePointer 
ElementType = MTLDataTypeStruct 
ElementTypeDescription = <MTLStructTypeInternal: …
```

Reflection fixes

---

src/sync.rs

This potentially fixes synchronization as these constants are passed to APIs like `waitForFence(_ fence: MTLFence, 
before stages: MTLRenderStages)`
https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1648378-waitforfence
Would appreciate if someone could properly double-check this. I can see from the metal frame capture that this fixed incorrect values for me, and these docs show the constants being used in other bindings. https://docs.microsoft.com/en-us/dotnet/api/metal.mtlrenderstages?view=xamarin-ios-sdk-12 I was not able to find the correct values published by apple. (Maybe their C++ bindings would have them)

Fix incorrect MTLRenderStages constants

---

Cargo.toml
examples/argument-buffer/main.rs
examples/bindless/main.rs
src/encoder.rs
src/resource.rs
src/sync.rs

This PR:
- Changes `MTLRenderStages` to bitflags as there are cases when we want to combine stages (below).
- Current `useResource` method is [deprecated](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/2866168-useresource). The [new one](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/3043404-useresource?language=objc) includes `stages` param.
- Adds `useResources` and `useHeaps` to pass slices of resources.
- Updates `argument-buffer` example to demonstrate how to use `use_resources`.
- Adds new `bindless` example that demonstrates how to bind lots of textures all at once with argument buffers.

Add new use resources methods

---

src/device.rs
src/library.rs

Trivial commit, `macOS_ReadWriteTextureTier2` feature is needed to fix wgpu's  `read_write_texture_tier` . 
Added two comments above `MTLFeatureSet` and `MTLGPUFamily` because someone confused the relationship between the two.

Add `V2_4` MTLLanguageVersion and `macOS_ReadWriteTextureTier2` feature

---

src/commandbuffer.rs

This is needed to fix the wgpu metal backend `push | pop_debug_group` implementation

Add `push | pop_debug_group` fn to CommandBuffer

---

src/lib.rs

While examining the release build assembly, I noticed a branch that precedes any call to an Objective-C parent type method.
For example, `color_attachment.set_texture(Some(texture));`...
```asm
...
Ltmp157:
mov	x0, x25
bl	__ZN101_$LT$metal..renderpass..RenderPassColorAttachmentDescriptorRef$u20$as$u20$core..ops..deref..Deref$GT$5deref17h157b1b3f5a4ba402E
Ltmp158:
Ltmp159:
mov	x1, x26
bl	__ZN5metal10renderpass33RenderPassAttachmentDescriptorRef11set_texture17he4f575ac4d07711eE
...
__ZN101_$LT$metal..renderpass..RenderPassColorAttachmentDescriptorRef$u20$as$u20$core..ops..deref..Deref$GT$5deref17h157b1b3f5a4ba402E:
.cfi_startproc
ret
.cfi_endproc
```
Seems like an easy improvement without requiring users to commit to LTO.

Add inline attribute to deref

---

src/encoder.rs

https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/2966552-memorybarrierwithresources?changes=_9&language=objc

Add memoryBarrierWithResources:count:

---

README.md
assets/metal.svg
src/argument.rs
src/buffer.rs
src/capturedescriptor.rs
src/capturemanager.rs
src/commandbuffer.rs
src/commandqueue.rs
src/constants.rs
src/depthstencil.rs
src/device.rs
src/drawable.rs
src/encoder.rs
src/heap.rs
src/indirect_encoder.rs
src/lib.rs
src/library.rs
src/mps.rs
src/pipeline/compute.rs
src/pipeline/mod.rs
src/pipeline/render.rs
src/renderpass.rs
src/resource.rs
src/sampler.rs
src/sync.rs
src/texture.rs
src/types.rs
src/vertexdescriptor.rs

1. Added links to Apple documentation for some structs, nearly all enums (except `MTLStructMemberArray` and `MTLStructMemberArray`), and some type definitions.
2. Explain away [docs.rs metal documentation](docs.rs/metal) build failure.
3. Add metal logo to README.
a. I just think it looks nice, if it's not in the spirit of the project I'd be fine with it going :)

Link to Apple Documentation, explain docs.rs failure

---

src/texture.rs

This PR adds a binding for the [`MTLTextureType2DMultisampleArray`](https://developer.apple.com/documentation/metal/mtltexturetype/mtltexturetype2dmultisamplearray?language=objc) texture type enum value.

Add `MTLTextureType::D2MultisampleArray`

---

src/commandbuffer.rs

This PR adds a binding for `MTLCommandBuffer` [addScheduledHandler](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1442991-addscheduledhandler?language=objc).

Add `add_scheduled_handler` method to `CommandBuffer`

---

guide/debugging-in-xcode/README.md
src/capturedescriptor.rs
src/capturemanager.rs
src/lib.rs

- Fixes setting/getting `MTLCaptureDescriptor` `outputURL` to an `NSString` instead of an `NSURL` (https://developer.apple.com/documentation/metal/mtlcapturedescriptor/3237250-outputurl?language=objc)
- Fixes casting `()` to `Result<(), String>` in `CaptureManager.start_capture`
- Adds documentation for capturing a GPU trace to a file without running from Xcode
These issues were causing a panic both when setting a CaptureDescriptor outputURL and when starting a capture using a CaptureDescriptor.
---
Example usage in a wgpu/winit program
```rust
// create capture scope using wgpu device
let capture_scope = unsafe {
device.as_hal::<api::Metal, _, _>(|device| {
let raw_device = device.unwrap().raw_device().lock();
metal::CaptureManager::shared().new_capture_scope_with_device(&raw_device)
}) …
```

Fix type issues in CaptureDescriptor and CaptureManager, add documentation

---

src/accelerator_structure.rs

Fairly straightforward.
Corresponding piece of "MTLAccelerationStructure.h":
```cpp
typedef struct {
/**
* @brief Transformation matrix describing how to transform the bottom-level acceleration structure.
*/
MTLPackedFloat4x3 transformationMatrix;
/**
* @brief Instance options
*/
MTLAccelerationStructureInstanceOptions options;
/**
* @brief Instance mask used to ignore geometry during ray tracing
*/
uint32_t mask;
/**
* @brief Used to index into intersection function tables
*/
uint32_t intersectionFunctionTableOffset;
/**
* @brief Acceleration structure index to use for this instance
*/
uint32_t accelerationStructureIndex;
/**
* @brief User-assigned instance ID to help identify this instance in an
* application-defined way
*/
uint32_t userID;
} …
```

Add MTLAccelerationStructureUserIDInstanceDescriptor

---

src/lib.rs

We should do this for the same reason it was done in: https://github.com/gfx-rs/metal-rs/pull/196 (calling functions which use this macro in an `autorelasepool` will cause a SIGSEGV since the obj has already been released manually).
Fixes the segfault encountered in: https://github.com/gfx-rs/wgpu/issues/3550.

Don't release the error obj manually

---

src/computepass.rs
src/counters.rs
src/encoder.rs

Introduced a bug in the last PR.
Looks like everything should be good to go here, the retain is no longer needed thanks to @Wumpf.

chore: Fix timestamp bug and add required method

---

Cargo.toml
src/accelerator_structure.rs
src/device.rs
src/encoder.rs
src/indirect_encoder.rs
src/library.rs
src/mps.rs
src/pipeline/render.rs
src/resource.rs
src/sync.rs
src/texture.rs

Changelog: https://github.com/bitflags/bitflags/blob/2.0.0/CHANGELOG.md#200.
This is a breaking change. The API that is implemented by the macro is now different.
I was a bit liberal with deriving `std` traits on public types, which mimics the behavior of `bitflags` v1, let me know if we don't need all these traits. Potentially we could at least drop `PartialOrd` and `Ord`.

Bump `bitflags` to v2

---

src/library.rs

I was getting crashes when interacting with libraries and I tracked it down to calling Library::function_names(). I barely understand the objc runtime and how rust binds with it, but I am suspicious that we are manually decrementing the ref count of an array of strings used internally by the MTLLibrary.
Here is example code that produced the crash consistently for me:
```rust
let library = device
.new_library_with_file("my_library.metallib")
.unwrap();
for function_name in library.function_names() {
println!("metal function {}", function_name);
}
println!("dropping library");
drop(library); // <-- Crashes if library.function_names() is called
println!("it's dropped");
```
Before this change, I would crash in the `drop(library)` call. (Other interactions with the Library could also elicit …

Fix undefined behavior caused by calling Library::function_names()

---

.github/workflows/ci.yml

The [actions-rs/cargo](https://github.com/actions-rs/cargo) and [actions-rs/toolchain](https://github.com/actions-rs/toolchain) are not maintained - replace them with [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain).
Motivated by the build failure in https://github.com/gfx-rs/metal-rs/actions/runs/5468319428/jobs/9955791906 (probably caused by [actions using node.js 12 starting to break](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/)).

Replace unmaintained actions-rs GitHub actions

---

examples/compute/main.rs

Improve the compute example to work on large array sizes by starting from the thread group size and calculate the thread group count, instead of the other way around (which can cause too large thread groups). This fixes #244.
Also make it possible to specify array size as argument and fix clippy warnings.

Improve the compute example to work on large array sizes

---

src/argument.rs
src/depthstencil.rs
src/device.rs
src/indirect_encoder.rs
src/lib.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/resource.rs
src/texture.rs

This fixes `warning: unreachable pattern` on `aarch64`, as seen when running e.g. `cargo clippy` or `cargo run --example compute`.
As suggested by [this comment](https://github.com/gfx-rs/metal-rs/pull/267#issuecomment-1509633887) in #267 (which this PR replaces).

Fix unreachable pattern warnings on aarch64

---

src/device.rs
src/encoder.rs
src/indirect_encoder.rs

Added:
- `Device::new_indirect_command_buffer_with_descriptor`
- `IndirectCommandBufferDescriptor::new`
- `BlitCommandEncoder::copy_indirect_command_buffer`
- `BlitCommandEncoder::reset_commands_in_buffer`
- `BlitCommandEncoder::optimize_indirect_command_buffer`
- `ArgumentEncoder::set_indirect_command_buffer`
- `ArgumentEncoder::set_indirect_command_buffers`
This makes indirect command buffers usable from metal-rs
Fixes #278

Add support for creating and using indirect command buffers

---

src/blitpass.rs
src/commandbuffer.rs
src/encoder.rs
src/lib.rs

* blit command encoder creation with descriptor
* expose `MTLCounterDontSample`
* add `sample_counters_in_buffer` for render command encoder

More timer query support

---

Cargo.toml

chore: update core-graphics-types

---

Cargo.toml
README.md
src/sync.rs

This one unused `objc_exception` dependency is preventing docs from building on docs.rs, because `cc` tries to pass `-arch`, to GCC, which doesn't see it as a valid argument, when building [`objc-exception`](https://github.com/SSheldon/rust-objc-exception/blob/master/build.rs).
Except, `objc-exception` doesn't really _do anything_ in metal-rs. I grepped for all of the [functions exported by `objc-exception`](https://github.com/SSheldon/rust-objc-exception/blob/master/src/lib.rs), and found nothing at all. I then ran 
* `cargo check --target=x86_64-apple-darwin`
* `cargo check --target=aarch64-apple-ios`
* `cargo check --target=aarch64-apple-darwin`
On both Windows and Linux and it passed with flying colours. To be sure, I checked the source of the [`objc` …

Remove unused `objc_exception` dependency

---

src/accelerator_structure.rs

Implements the `MTLIndirectAccelerationStructureInstanceDescriptor` struct, the `MTLIndirectInstanceAccelerationStructureDescriptor` struct with all its setter functions. Also implements fetching an acceleration structure's GPU resource id, since we need that to fill in the `MTLIndirectAccelerationStructureInstanceDescriptor`

Implement indirect instance acceleration structure

---

src/accelerator_structure.rs
src/encoder.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs

Implements `MTLVisibleFunctionTableDescriptor`, creating a visible function table on a pipeline, as well as the different `setVisibleFunctionTable` functions in the command encoders.

Implement Visible Function Table

---

src/device.rs
src/heap.rs

Implements allocating acceleration structures from a heap using the `newAccelerationStructureWithDescriptor` and `newAccelerationStructureWithSize` functions, as well as `heapAccelerationStructureSizeAndAlignWithSize` on Device. Additionally implements two missing functions `setHazardTrackingMode` and `setType`.

Implement creating acceleration structures on a `Heap`

---

src/accelerator_structure.rs

These return a +0 autoreleased pointer, so we have to retain them ourselves before we put them in the strong smart pointer created by `foreign_obj_type!`.
Fixes https://github.com/gfx-rs/metal-rs/issues/319.

Fix accelerator structure `descriptor` methods

---

.github/workflows/ci.yml

This updates these to the current versions which also use more recent versions of Node, silencing some deprecation warnings from within GitHub Actions.

ci: Update `actions/checkout` and `actions/cache`.

---

src/argument.rs

Adds all the missing enum variants for MTLDataType, including 64 bit integers, pipelines, indirect command buffer, ray tracing related types, and BFloat.

Add missing enum variants for MTLDataType

---

src/accelerator_structure.rs
src/device.rs
src/encoder.rs
src/indirect_encoder.rs
src/lib.rs
src/library.rs
src/mps.rs
src/pipeline/render.rs
src/resource.rs
src/sync.rs
src/texture.rs

Also, switch away from `#[macro_use]` and `extern crate` for these crates.

Don't re-export `bitflags` and `log`.

---

src/drawable.rs

Rebased #300
GitHub closed the original PR automatically while I was rebasing the PR - probably because I was trying to push the new commit to the remote `master` and there's some kind of special handling for default branches

Add `presented_time` to `MTLDrawable`

---

src/accelerator_structure.rs

Adds the following two functions:
- `AccelerationStructureBoundingBoxGeometryDescriptor::set_bounding_box_stride`
- `AccelerationStructureBoundingBoxGeometryDescriptor::set_bounding_box_buffer_offset`

Add `set_bounding_box_stride` and `set_bounding_box_buffer_offset` to `AccelerationStructureBoundingBoxGeometryDescriptor`

---

Cargo.toml

Expands the set of Mac targets to cover more Mac toolchains. 😀
<details><summary>Original OP text from draft</summary>
We've specified a `default-target` for `docs.rs` metadata in `Cargo.toml`, but the way to exclude other platforms is via the `targets` field, according to [these docs][targets-docs] on it:
> ```
> # If `default-target` is unset, the first element of `targets` is treated as the default target.
> # Otherwise, these `targets` are built in addition to the default target.
> # If both `default-target` and `targets` are unset,
> #   all tier-one targets will be built and `x86_64-unknown-linux-gnu` will be used as the default target.
> ```
[targets-docs]: https://web.archive.org/web/20230528205129/https://docs.rs/about/metadata
---
~~Should fix #5.~~ EDIT: [Maybe …

build(docs.rs): cover more Mac targets

---

Cargo.toml

When the `link` feature was forwarded to `core-graphics-types` in its update in https://github.com/gfx-rs/metal-rs/pull/297, it wasn't taken into account that  the feature was enabled by default in https://togithub.com/servo/core-foundation-rs/pull/608, leading to the `link` feature to always remain enabled even if `default-features` are **disabled** on the `metal` crate.
Disable the `link` feature by default on `core-graphics-types`, and rely on our (default-enabled) `link` feature to turn it back on from inside `metal`.

Disable default `link` feature on `core-graphics-types`

---

src/computepass.rs

See https://developer.apple.com/documentation/metal/mtlcomputepassdescriptor/3564435-dispatchtype?language=objc
Tested manually.

Add ComputePassDescriptorRef::set_dispatch_type

---

Cargo.toml
examples/circle/main.rs

This can be replaced with using `std::ffi` instead. This was added in Rust 1.64, but doesn't impact our MSRV as the examples use winit and glam, which have MSRVS of 1.65 and 1.68.2 respectively for the versions used at the time of this commit.

Remove dev-dependency `cty`

---

src/counters.rs

Tested manually in https://github.com/kvark/blade/pull/179

Add CounterSampleBuffer::resolve_counter_range

---

src/sampler.rs

According to the upstream docs and the Metal Shader Converter implementation the `SamplerState` type has a way to get access to its `MTLResourceID` on the GPU: https://developer.apple.com/documentation/metal/mtlsamplerstate/3974101-gpuresourceid

sampler: Add missing `gpu_resource_id()` getter

---

src/device.rs

While looking at a copy of this code (in another project that uses `objc2`, which does not yet define `dispatch` integration) this strange cast immediately stands out.  `_dispatch_main_q` is defined here as a `dispatch_queue_t`, the `queue` argument in `dispatch_data_create()` is also defined as a `dispatch_queue_t`, yet there is a "borrow" (get *pointer to*) operation before passing it into the function.
Instead, this `static` field is supposed to be defined as the `Object` itself, so that any user could take a _pointer to it_ if they wish or need it so.  The same is seen in [the `dispatch` crate]: `_dispatch_main_q` is defined as a `dispatch_object_s`, and `dispatch_queue_t` is a _typedef_ to a `*mut dispatch_object_s` to match the above convention.
Note that this is not a bugfix, but …

Fix wrong pointer type of `static _dispatch_main_q` binding

---

.github/workflows/ci.yml
Cargo.toml
examples/circle/main.rs
examples/compute/compute-argument-buffer.rs
examples/compute/main.rs
examples/headless-render/main.rs
examples/mps/main.rs
examples/raytracing/geometry.rs
examples/raytracing/renderer.rs
examples/raytracing/scene.rs
examples/texture/src/main.rs
examples/window/main.rs
src/counters.rs
src/device.rs
src/sync.rs

Following https://github.com/gfx-rs/metal-rs/pull/343#issuecomment-2708428426
This also makes use of `size_of(_val)()` being imporced via the prelude, `&raw` pointers being available to - for example - save on casts from borrows to raw pointers, and C-string literals automatically appending NUL terminators to strings.

Set and test MSRV at 1.82

---

.gitignore

These files can be generated while compiling Metal shaders via `build.rs`, so ignore them, too.

chore(.gitignore): ignore `**/*.air.tmp`

---

examples/compute/compute-argument-buffer.rs
examples/compute/main.rs
examples/raytracing/renderer.rs

Noticed that one more pointer was being transmuted to another type rather than using a trivial cast, before `unsafe`ly dereferencing it.
This also removes the `ptr::read()` syntax introduced in #344 again, in favour of using a simple and more standard `*` deref.

examples: Replace one more `unsafe transmute()` with trivial `ptr::cast()`
