gfx-rs/metal-rs

src/device.rs

Allows the creation of a MTLLibrary from a precompiled .metallib file.

Added new_library_with_file to MTLDevice

---

.travis.yml
Cargo.toml
examples/argument-buffer/main.rs
examples/window/main.rs
src/device.rs
src/lib.rs
src/resource.rs

A continuation of https://github.com/gfx-rs/metal-rs/pull/16

Argument buffer fix

---

src/constants.rs

Add missing constants from MTLPixelFormat, make it Eq

---

src/device.rs

There were a few missing (and the website mentioned some beta's that are being added in the future).

Adding missing MTLFeatureSets

---

src/device.rs

I thought I'd check that this is a sensible approach before I finished going through the feature tables as it's a bit tedious. As far as I can tell there is no nice source of this information bar the feature table pdf, I would love to know if anyone has found any other sources.

Add feature set queries

---

Cargo.toml
README.md
examples/argument-buffer/main.rs
examples/caps/main.rs
examples/compute/compute-argument-buffer.rs
examples/compute/embedded-lib.rs
examples/compute/main.rs
examples/library/main.rs
examples/reflection/main.rs
examples/window/main.rs

Fixes #65
If this seems alright, let me know and I can publish it.

Deprecate metal-rs

---

src/encoder.rs

Fix set_fragment_textures

---

src/commandbuffer.rs
src/device.rs
src/encoder.rs
src/pipeline/render.rs
src/renderpass.rs
src/types.rs

Add missing MTLSamplePosition

---

Cargo.toml
examples/window/main.rs
src/device.rs
src/library.rs

Fix library name leak

---

.gitignore
Cargo.toml
examples/argument-buffer/main.rs
src/lib.rs

This PR has essential fixes (2 of them!) to get the argument-buffer example running correctly.

Fix Array initialization

---

Cargo.toml
src/argument.rs
src/capturemanager.rs
src/commandbuffer.rs
src/commandqueue.rs
src/device.rs
src/encoder.rs
src/lib.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/resource.rs

These commits fix the remaining leaks that I could identify

Fix mem leaks

---

src/device.rs

When use ```aarch64-apple-ios``` buid and debug on iOS device, Xcode alway Throw error: ```Undefined symbols for architecture arm64:
"_MTLCopyAllDevices"```

Debug on iOS device, Xcode alway Throw error

---

examples/argument-buffer/main.rs
examples/bind/main.rs
examples/compute/compute-argument-buffer.rs
examples/compute/embedded-lib.rs
examples/compute/main.rs
examples/reflection/main.rs
examples/window/main.rs
src/capturemanager.rs
src/commandbuffer.rs
src/commandqueue.rs
src/device.rs
src/encoder.rs
src/heap.rs
src/lib.rs
src/library.rs
src/pipeline/compute.rs
src/pipeline/render.rs
src/renderpass.rs
src/resource.rs

Add explicit return types for `msg_send!` calls

---

Cargo.toml
src/pipeline/compute.rs
src/pipeline/mod.rs
src/pipeline/render.rs

This is required for https://github.com/gfx-rs/gfx/issues/1999

Expose buffer mutability on render pipelines

---

Cargo.toml
examples/circle/main.rs
examples/texture/src/main.rs
examples/window/main.rs
src/lib.rs

Remove core-graphics dependency

---

src/capturedescriptor.rs
src/capturemanager.rs
src/lib.rs

This PR adds the `CaptureDescriptor`, closing #153

Add CaptureDescriptor

---

src/encoder.rs

https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400748-generatemipmaps

added method MTLBlitCommandEncoder::generate_mipmaps

---

src/types.rs

This was originally #165 but I pushed more than I wanted so here we go again.

mtlregion constructors

---

src/device.rs

Add the following APIs:
https://developer.apple.com/documentation/metal/mtldevice/3114006-locationnumber
https://developer.apple.com/documentation/metal/mtldevice/3114005-location
https://developer.apple.com/documentation/metal/mtldevicelocation

Add DeviceRef::{location, location_number} and MTLDeviceLocation

---

Cargo.toml
src/device.rs
src/encoder.rs
src/lib.rs
src/library.rs
src/mps.rs
src/sync.rs

Sorry for dubious description. 
This MR is result of me working with metal-rs on some rendering code and adding missing API elements as I needed them.
I will continue this as I find the time, and in the meantime would appreciate considering merging what I got so far.
Feel free to ask me to cleanup some things (I ran into merge conflicts, as some of the functionality was being added by your team at the same time). I noticed some inconsistencies with enum naming and was not sure whether to follow Apple's or yours.
Thanks

Various missing bits and bobs

---

guide/README.md
guide/internals/README.md

https://github.com/gfx-rs/metal-rs/issues/148#issuecomment-656812190

Move wiki to guide

---

src/pipeline/compute.rs
src/pipeline/render.rs

Remove pipeline set_label

---

src/argument.rs
src/device.rs

Fix MTLArgumentType and MTLArgumentAccess size

---

src/drawable.rs

This PR exposes Drawable ID for MTLDrawable
https://developer.apple.com/documentation/metal/mtldrawable/2806860-drawableid?language=objc

Expose Drawable ID

---

src/device.rs
src/renderpass.rs

A few minor fixes

---

src/accelerator_structure.rs

See https://developer.apple.com/documentation/metal/mtlaccelerationstructuregeometrydescriptor/3666579-opaque?language=objc

Expose AccelerationStructureGeometryDescriptorRef::set_opaque

---

Cargo.toml
src/device.rs
src/mps.rs

This PR adds a feature to disable linking for allow to weak link

feat: link feature

---

src/accelerator_structure.rs

Implements the missing features for acceleration structure command encoders.

Implement missing functions for acceleration structure command encoder

---

src/accelerator_structure.rs
src/pipeline/render.rs

Implements some missing Intersection Function Table related functions.

Implement missing functions for Intersection Function Table

---

src/drawable.rs

Add the `add_presented_handler` function to `Drawable`
https://developer.apple.com/documentation/metal/mtldrawable/2806858-addpresentedhandler

Add `add_presented_handler` to `Drawable`

---

src/device.rs

Fix visionos cfgs

---

src/texture.rs

Needed for image atomics https://github.com/gfx-rs/wgpu/pull/5537

Add ShaderAtomic to MTLTextureUsage

---

README.md
src/lib.rs

Deprecate the crate explicitly
